Server:
  RunMode: debug
  HttpPort: 8080
  ReadTimeout: 60
  WriterTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
Database:
  DBType: mysql
  Username: root
  Password: root
  Host: 127.0.0.1:3306
  DBName: ck_blog
  TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConnes: 10
  MaxOpenConnes: 30